# ==========================================
# 1. 剧本/文本评估提示词 (Narrative Scripts Evaluation - Table 1)
# ==========================================

NARRATIVE_EVAL_PROMPT = """Please act as an impartial and expert Visual Novel (VN) narrative designer and critic. Your task is to evaluate the quality of interactive scripts generated by two different AI systems (System A and System B) based on the same underlying theme and storyline.

Anti-Bias Instructions:
1. Position Bias: Avoid any position biases. Ensure that the order in which the scripts are presented does not influence your decision.
2. Length Bias: Do not allow the length of the scripts to dominate your evaluation. A longer script is not necessarily better if it contains repetitive dialogue or logical hallucinations. Focus on the density and quality of the narrative.

Inputs Provided to You:
1. Global Outline & Character Persona: {global_outline_and_persona}
2. Previous Context (if applicable): {previous_context}
3. Script A: {script_a}
4. Script B: {script_b}

Evaluation Dimensions:
Please evaluate the two scripts across the following four dimensions:

1. Coherence: Assess the causal and logical consistency of the narrative. Does the script logically follow the Previous Context without hallucinating facts, forgetting constraints, or causing causal collapse? 

2. Char. Fidelity (Character Fidelity): Evaluate how well the characters' dialogue and actions align with the provided Character Persona. Do the characters maintain their unique speaking styles, motivations, and standpoints, or do they exhibit Out-Of-Character (OOC) behaviors?

3. Interestingness: Assess the originality and engagement of the plot. Is the narrative compelling? Does it avoid boring cliches while providing unexpected yet reasonable developments?

4. Playability: Evaluate the interactive experience. Are the branching choices presented to the player meaningful and impactful? Does the scene effectively drive the interactive plot forward?

Output Format:
For each dimension, you must output your evaluation following a strict Chain-of-Thought (CoT) format. First, provide a detailed comparative analysis, then output the final verdict.

Please format your response strictly as follows:
<coherence_analysis> Your detailed comparison regarding coherence. </coherence_analysis>
<coherence_verdict> A or B or TIE </coherence_verdict>

<char_fidelity_analysis> Your detailed comparison regarding character fidelity. </char_fidelity_analysis>
<char_fidelity_verdict> A or B or TIE </char_fidelity_verdict>

<interestingness_analysis> Your detailed comparison regarding interestingness. </interestingness_analysis>
<interestingness_verdict> A or B or TIE </interestingness_verdict>

<playability_analysis> Your detailed comparison regarding playability. </playability_analysis>
<playability_verdict> A or B or TIE </playability_verdict>"""


# ==========================================
# 2. 视觉资产评估提示词 (Visual Assets Evaluation - Table 2)
# ==========================================

VISUAL_EVAL_PROMPT = """Please act as an impartial and expert Visual Novel (VN) director. Your task is to evaluate the quality of multimedia assets (e.g., character sprites, CGs) generated by two different AI systems (System A and System B) for a specific narrative scene.

Anti-Bias Instructions:
1. Avoid any position biases. Ensure that the order in which the images are presented does not influence your decision.
2. Evaluate solely based on the provided narrative context, character persona, and the visual execution of the images.

Inputs Provided to You:
1. Character Persona & Outline: {character_persona}
2. Current Script/Dialogue: {current_script}
3. Image A: (Attached)
4. Image B: (Attached)

Evaluation Dimensions:
Please evaluate the two images across the following three dimensions:

1. Visual Quality: Assess the aesthetic appeal, image clarity, and structural correctness (e.g., absence of distorted limbs, weird artifacts, or unnatural lighting). Which image looks more like a professionally drawn visual novel asset?

2. Persona Alignment: Evaluate how well the character's facial expression, body language, and temperament in the image match the provided Character Persona and the emotional tone of the Current Script. Does the image capture the nuanced emotion (e.g., a subtle pout, a bittersweet smile) required by the dialogue without being Out-Of-Character (OOC)?

3. Consistency: Assess the cross-modal consistency. Does the character's outfit, age, and style consistently match the textual descriptions? Is the visual style coherent with standard anime-inspired visual novel aesthetics?

Output Format:
For each dimension, you must output your evaluation following a strict Chain-of-Thought (CoT) format. First, provide a detailed comparative analysis, then output the final verdict.

Please format your response strictly as follows:
<visual_quality_analysis> Your detailed comparison regarding visual quality. </visual_quality_analysis>
<visual_quality_verdict> A or B or TIE </visual_quality_verdict>

<persona_alignment_analysis> Your detailed comparison regarding persona alignment. </persona_alignment_analysis>
<persona_alignment_verdict> A or B or TIE </persona_alignment_verdict>

<consistency_analysis> Your detailed comparison regarding consistency. </consistency_analysis>
<consistency_verdict> A or B or TIE </consistency_verdict>"""